export const content = {
  en: {
    locale: 'en', otherLocale: 'fr', languageName: 'Français',
    title: 'Sorcova Health | Your health, for the long run',
    description: 'Stress resilience, mental wellbeing and whole-person health. A personal, physician-led approach to healthy longevity, for you and your people.',
    skip: 'Skip to content', home: 'Sorcova Health home', menu: 'Menu', close: 'Close',
    nav: { approach: 'Our approach', members: 'For members', employers: 'For employers', science: 'Science & care' },
    hero: {
      label: 'A healthier you. A fuller life.',
      title: ['More life', 'in your days.', 'More you.'],
      text: 'Your mind, your body, your life. Connected. Sorcova brings stress resilience, mental wellbeing and everyday health into one personal, physician-led approach.',
      memberCta: 'Explore for yourself', employerCta: 'Explore for your team',
      alt: 'AI-generated brand image of a woman smiling softly in the morning light on an airy garden terrace.',
      caption: 'Health for the life you want to live.',
      noteTitle: 'Feel well today.', noteText: 'Think beyond tomorrow.',
      scroll: 'Discover the Sorcova approach',
    },
    trust: ['Physician-led guidance', 'Built around your usual', 'Privacy by design'],
    whole: {
      label: 'The whole of you', title: 'Not just less stress.\nMore room for life.',
      text: 'Stress is part of the picture. So are your mental wellbeing, physical health and the way you want to live as you grow older. We bring them into the same conversation.',
      pillars: [
        { title: 'Stress & resilience', text: 'Understand your patterns of pressure, rest and recovery.', icon: 'waves' },
        { title: 'Mental wellbeing', text: 'Make space for your mood, connection and emotional life.', icon: 'brain' },
        { title: 'Whole-body health', text: 'Bring sleep, movement, nutrition and energy into view.', icon: 'heart' },
        { title: 'Healthy longevity', text: 'Keep the longer view in mind, through everyday habits.', icon: 'plant' },
      ],
      closing: 'Different parts of your health. One personal picture.',
    },
    audiences: {
      label: 'Different starting points. A shared ambition.',
      title: 'Personal health.\nCollective possibility.',
      text: 'Whether you are here for yourself or the people you work with, it starts with understanding the person.',
      members: {
        label: 'For members', title: 'Feel more connected\nto your health.',
        text: 'A fuller understanding of your mental and physical wellbeing. Personal guidance that connects how you feel today with the health you want to nurture over time.',
        items: ['A baseline that learns what is usual for you', 'Small, personal steps that fit your rhythm', 'Clinical decisions reviewed by a physician'],
        cta: 'Let’s talk about you',
      },
      employers: {
        label: 'For employers', title: 'Put people at the heart\nof workplace health.',
        text: 'Give your people access to a personal, physician-led programme. Understand the collective picture while keeping individual health information private.',
        items: ['A personal experience for each member', 'An aggregated view for your organisation', 'A guided conversation about your team’s needs'],
        cta: 'Let’s talk about your team',
      },
    },
    approach: {
      label: 'The Sorcova approach', title: 'A fuller picture.\nA more personal path.',
      text: 'Your day, your body and your context belong together. Sorcova connects the signals, with a clinician there to interpret what matters.',
      signals: [
        { title: 'Your everyday check-ins', tag: 'Listen', text: 'Short reflections on sleep, energy, mood and stress. Just enough to understand how your day feels.', shape: 'check-in' },
        { title: 'Your wearable signals', tag: 'Connect', text: 'Patterns in sleep, heart-rate variability and resting heart rate, considered against your own usual.', shape: 'wearable' },
        { title: 'Your stress lab kit', tag: 'Understand', text: 'A saliva kit adds another perspective. A physician interprets the results and releases your signed report.', shape: 'lab' },
      ],
      footTitle: 'Your baseline, not someone else’s.',
      footText: 'Sorcova takes time to learn your usual. When there is not enough information, it says so instead of guessing.',
    },
    everyday: {
      label: 'Wellbeing, lived every day', title: 'A longer view.\nAn everyday beginning.',
      text: 'Sleep, nourishment, movement, time outside and connection. Healthy longevity starts with paying attention to the life you actually live.',
      tabsLabel: 'Explore everyday wellbeing',
      motion: {
        disclaimer: 'Illustrative rhythms. Not live health readings.',
        descriptions: ['A gentle cycle of settling and rest.', 'A flowing rise and release of energy.', 'Slow, expanding waves of recovery.', 'Softly connected patterns, finding a rhythm.'],
      },
      tabs: [
        { id: 'sleep', label: 'Sleep', title: 'Make room for rest.', text: 'Your evenings, mornings and changing routines all add context. Sorcova helps you understand patterns in your sleep, in relation to your own usual.', detail: 'A personal picture of sleep and rhythms.', words: ['Evenings', 'Rest', 'Mornings'] },
        { id: 'energy', label: 'Energy', title: 'Understand your own pace.', text: 'How you feel can change from day to day. Your check-ins help put those changes in context, alongside the rhythm of your daily life.', detail: 'Energy and vitality, understood in context.', words: ['Movement', 'Energy', 'Recovery'] },
        { id: 'recovery', label: 'Recovery', title: 'Space to find your balance.', text: 'Work, travel and everyday demands are part of the picture. Sorcova considers what is happening around you when looking at your patterns over time.', detail: 'Stress and recovery, with your life in view.', words: ['Work', 'Pause', 'Connection'] },
        { id: 'mind', label: 'Mind & mood', title: 'A little space for how you feel.', text: 'Your own words matter. Short check-ins bring your experience of mood and stress into a conversation that stays personal and clinician-governed.', detail: 'Mind and emotions, in your own words.', words: ['Check in', 'Reflect', 'Reconnect'] },
      ],
      avaTitle: 'Ava, your guide',
      avaText: 'Designed to turn patterns into plain language, using insights signed by clinicians. Clinical decisions stay with people.',
    },
    care: {
      label: 'Science with a human centre', title: 'Technology notices.\nPeople understand.',
      text: 'A signal is only part of the story. Physicians bring the clinical context, review laboratory results and release changes to your plan.',
      founder: 'Founded by Dr Lavinia Ionita', founderRole: 'Physician and founder of Sorcova',
      cards: [
        { title: 'Clinical oversight', text: 'Clinical rules and insight wording are signed by a physician. Meaningful changes remain under human review.' },
        { title: 'Honest about confidence', text: 'Guidance reflects what the information can support. Uncertainty is expressed in plain words.' },
        { title: 'Evidence-minded, always', text: 'Validation studies are planned or in progress. Sorcova does not claim published clinical outcomes.' },
      ],
    },
    privacy: {
      label: 'Personal means private', title: 'Your health is personal.\nIt stays that way.',
      text: 'Members, clinicians and employers have different needs. Their views are kept separate by design.',
      items: [
        { title: 'For you', text: 'Plain-language guidance about your own patterns.' },
        { title: 'For your clinician', text: 'The clinical detail needed to review and interpret.' },
        { title: 'For your employer', text: 'Collective trends, never your individual health results.' },
      ],
    },
    faq: {
      title: 'A few things you\nmight be wondering.',
      intro: 'A clearer starting point, for you and your organisation.',
      items: [
        { q: 'Is Sorcova only about stress?', a: 'No. Stress is an important starting point, not the whole story. Sorcova connects stress resilience, mental wellbeing and physical health with a longer-term perspective on healthy living. Sleep, movement, nutrition, recovery and connection all have a place. Individuals and organisations can both explore a programme.' },
        { q: 'What happens when I start?', a: 'A guided introduction helps Sorcova get to know you. A foundation phase then builds your personal baseline. During that phase, the focus is on engagement and progress, before personal readings are available.' },
        { q: 'What does the stress lab kit tell me?', a: 'The saliva kit provides laboratory information for a physician to review. Your Stress Signature is shared through a physician-signed report. The kit alone does not provide a diagnosis or an in-app clinical tier.' },
        { q: 'Does Ava replace a clinician?', a: 'No. Ava is a guide, designed to use clinically signed language. She is not a doctor and does not give medical advice. Clinical decisions remain with a physician.' },
        { q: 'Can my employer see my results?', a: 'No. Individual health results are not shared with your employer. The employer view is designed for aggregated trends, separate from your personal and clinical information.' },
        { q: 'How can our organisation get started?', a: 'Start with a conversation about your people, your priorities and the scope of a programme. Together, we can explore what an appropriate introduction to Sorcova would look like.' },
      ],
    },
    closing: { label: 'Your next chapter', title: 'Your health.\nFor the long run.', text: 'A personal beginning. A bigger picture. For you and for the people you work with.', member: 'Let’s talk about you', employer: 'Let’s talk about your team' },
    footer: { tagline: 'Cultivating healthy longevity.', privacy: 'Our privacy approach', faq: 'Common questions', top: 'Back to top', copyright: 'Sorcova Health', language: 'Choose your language' },
    contact: {
      title: 'Let’s find your starting point.',
      memberTitle: 'A conversation about you.', employerTitle: 'A conversation about your team.',
      memberText: 'Tell us what you would like to explore. Please do not include medical information.',
      employerText: 'Tell us a little about your organisation and what you would like to explore. Please do not include anyone’s health information.',
      name: 'Your name', email: 'Your email', organisation: 'Organisation', message: 'What would you like to explore?', optional: 'Optional',
      submit: 'Prepare email', save: 'Save enquiry draft',
      draftNote: 'This saves a draft to your device. Nothing is sent to Sorcova.',
      emailNote: 'Opens your email app with a draft for you to review and send.',
      saved: 'Your enquiry draft has been downloaded. Nothing has been sent.',
      prepared: 'Review and send your draft in your email app. Nothing is sent automatically.',
      fallback: 'If your email app does not open, you can save your draft instead.',
      subjectMember: 'An enquiry about Sorcova for me', subjectEmployer: 'An enquiry about Sorcova for our organisation',
    },
    notFound: { title: 'A little off the path.', text: 'This page could not be found. Let’s get you back to Sorcova.', link: 'Back to the homepage' },
  },
  fr: {
    locale: 'fr', otherLocale: 'en', languageName: 'English',
    title: 'Sorcova Health | Votre santé, dans la durée',
    description: 'Résilience au stress, bien-être mental et santé globale. Une approche personnelle et médicale de la longévité en bonne santé, pour vous et vos équipes.',
    skip: 'Aller au contenu', home: 'Accueil Sorcova Health', menu: 'Menu', close: 'Fermer',
    nav: { approach: 'Notre approche', members: 'Pour les membres', employers: 'Pour les entreprises', science: 'Science et soins' },
    hero: {
      label: 'Une meilleure santé. Une vie plus épanouie.',
      title: ['Plus de vie', 'dans vos jours.', 'Plus de vous.'],
      text: 'Votre esprit, votre corps, votre vie. Tout est lié. Sorcova réunit résilience au stress, bien-être mental et santé au quotidien dans une approche personnelle, encadrée par des médecins.',
      memberCta: 'Découvrir pour vous', employerCta: 'Découvrir pour vos équipes',
      alt: 'Image de marque générée par IA : une femme sourit doucement dans la lumière du matin, sur une terrasse ouverte sur un jardin.',
      caption: 'La santé, pour la vie que vous souhaitez vivre.',
      noteTitle: 'Le bien-être aujourd’hui.', noteText: 'Un regard vers demain.',
      scroll: 'Découvrir l’approche Sorcova',
    },
    trust: ['Un accompagnement médical', 'Votre rythme comme repère', 'La confidentialité par conception'],
    whole: {
      label: 'Vous, dans votre ensemble', title: 'Pas seulement moins de stress.\nPlus de place pour la vie.',
      text: 'Le stress fait partie du tableau. Votre bien-être mental, votre santé physique et la façon dont vous souhaitez avancer en âge aussi. Nous les réunissons dans un même échange.',
      pillars: [
        { title: 'Stress et résilience', text: 'Comprendre vos rythmes de sollicitation, de repos et de récupération.', icon: 'waves' },
        { title: 'Bien-être mental', text: 'Faire place à votre humeur, à vos liens et à votre vie émotionnelle.', icon: 'brain' },
        { title: 'Santé globale', text: 'Relier sommeil, mouvement, alimentation et énergie.', icon: 'heart' },
        { title: 'Longévité en bonne santé', text: 'Garder une perspective à long terme, à travers les habitudes du quotidien.', icon: 'plant' },
      ],
      closing: 'Les différentes facettes de votre santé. Une vision personnelle.',
    },
    audiences: {
      label: 'Des points de départ différents. Une ambition commune.',
      title: 'Une santé personnelle.\nUne ambition collective.',
      text: 'Que vous soyez ici pour vous ou pour les personnes avec qui vous travaillez, tout commence par la compréhension de chacun.',
      members: {
        label: 'Pour les membres', title: 'Renouer avec\nvotre santé.',
        text: 'Une compréhension plus complète de votre bien-être mental et physique. Un accompagnement personnel qui relie votre ressenti actuel à la santé que vous souhaitez cultiver dans la durée.',
        items: ['Un repère qui apprend ce qui est habituel pour vous', 'Des petits pas adaptés à votre rythme', 'Des décisions cliniques revues par un médecin'],
        cta: 'Parlons de vous',
      },
      employers: {
        label: 'Pour les entreprises', title: 'Placer les personnes au cœur\nde la santé au travail.',
        text: 'Donnez à vos équipes accès à un programme personnel, dirigé par des médecins. Comprenez les tendances collectives tout en préservant les informations de santé individuelles.',
        items: ['Une expérience personnelle pour chaque membre', 'Une vision agrégée pour votre organisation', 'Un échange sur les besoins de vos équipes'],
        cta: 'Parlons de vos équipes',
      },
    },
    approach: {
      label: 'L’approche Sorcova', title: 'Une vision plus complète.\nUn chemin plus personnel.',
      text: 'Votre journée, votre corps et votre contexte forment un tout. Sorcova relie les signaux, avec un médecin pour interpréter ce qui compte.',
      signals: [
        { title: 'Vos bilans du quotidien', tag: 'Écouter', text: 'De courts échanges sur le sommeil, l’énergie, l’humeur et le stress. Juste ce qu’il faut pour comprendre votre vécu.', shape: 'check-in' },
        { title: 'Les signaux de votre montre', tag: 'Relier', text: 'Les tendances du sommeil, de la variabilité cardiaque et de la fréquence cardiaque au repos, comparées à vos habitudes.', shape: 'wearable' },
        { title: 'Votre kit biologique du stress', tag: 'Comprendre', text: 'Un kit salivaire apporte un autre éclairage. Un médecin interprète les résultats et vous remet un compte rendu signé.', shape: 'lab' },
      ],
      footTitle: 'Votre référence, pas celle d’un autre.',
      footText: 'Sorcova prend le temps de connaître votre rythme habituel. Lorsque les informations manquent, elle le dit plutôt que de deviner.',
    },
    everyday: {
      label: 'Le bien-être au quotidien', title: 'Voir plus loin.\nCommencer chaque jour.',
      text: 'Sommeil, alimentation, mouvement, nature et liens. La longévité en bonne santé commence par une attention à la vie que vous menez réellement.',
      tabsLabel: 'Explorer le bien-être au quotidien',
      motion: {
        disclaimer: 'Rythmes illustratifs. Aucune mesure de santé en direct.',
        descriptions: ['Un cycle doux entre apaisement et repos.', 'Un mouvement fluide entre élan et relâchement.', 'De lentes vagues de récupération qui se déploient.', 'Des mouvements reliés qui trouvent leur rythme.'],
      },
      tabs: [
        { id: 'sleep', label: 'Sommeil', title: 'Faire place au repos.', text: 'Vos soirées, vos matins et vos changements de routine apportent du contexte. Sorcova vous aide à comprendre les tendances de votre sommeil par rapport à vos habitudes.', detail: 'Une vision personnelle du sommeil et des rythmes.', words: ['Soirées', 'Repos', 'Matins'] },
        { id: 'energy', label: 'Énergie', title: 'Comprendre votre propre tempo.', text: 'Votre ressenti peut changer d’un jour à l’autre. Vos bilans aident à replacer ces variations dans le contexte de votre vie quotidienne.', detail: 'L’énergie et la vitalité, comprises dans leur contexte.', words: ['Mouvement', 'Énergie', 'Récupération'] },
        { id: 'recovery', label: 'Récupération', title: 'Un espace pour retrouver l’équilibre.', text: 'Travail, voyages et sollicitations quotidiennes font partie du tableau. Sorcova tient compte de votre contexte pour regarder vos tendances dans la durée.', detail: 'Le stress et la récupération, avec votre vie en perspective.', words: ['Travail', 'Pause', 'Liens'] },
        { id: 'mind', label: 'Humeur', title: 'Une place pour votre ressenti.', text: 'Vos mots comptent. De courts bilans intègrent votre vécu de l’humeur et du stress dans un échange qui reste personnel et encadré par des cliniciens.', detail: 'L’esprit et les émotions, avec vos propres mots.', words: ['Échanger', 'Réfléchir', 'Se retrouver'] },
      ],
      avaTitle: 'Ava, votre guide',
      avaText: 'Conçue pour expliquer les tendances avec des mots simples, à partir de contenus signés par des cliniciens. Les décisions cliniques restent humaines.',
    },
    care: {
      label: 'La science, avec l’humain au centre', title: 'La technologie observe.\nL’humain comprend.',
      text: 'Un signal ne raconte pas toute l’histoire. Les médecins apportent le contexte clinique, examinent les résultats biologiques et valident les évolutions de votre programme.',
      founder: 'Fondé par le Dr Lavinia Ionita', founderRole: 'Médecin et fondatrice de Sorcova',
      cards: [
        { title: 'Un encadrement médical', text: 'Les règles cliniques et les formulations sont signées par un médecin. Les changements importants restent soumis à une revue humaine.' },
        { title: 'Une confiance expliquée', text: 'L’accompagnement reflète ce que les informations permettent de dire. L’incertitude est exprimée avec des mots simples.' },
        { title: 'Une exigence scientifique', text: 'Des études de validation sont prévues ou en cours. Sorcova ne revendique pas de résultats cliniques publiés.' },
      ],
    },
    privacy: {
      label: 'Personnel signifie confidentiel', title: 'Votre santé est personnelle.\nElle le reste.',
      text: 'Les membres, les cliniciens et les employeurs ont des besoins différents. Leurs vues sont séparées dès la conception.',
      items: [
        { title: 'Pour vous', text: 'Un accompagnement en mots simples sur vos propres tendances.' },
        { title: 'Pour votre médecin', text: 'Le détail clinique nécessaire à l’examen et à l’interprétation.' },
        { title: 'Pour votre employeur', text: 'Des tendances collectives, jamais vos résultats de santé individuels.' },
      ],
    },
    faq: {
      title: 'Quelques questions\nque vous vous posez peut-être.',
      intro: 'Un point de départ plus clair, pour vous et votre organisation.',
      items: [
        { q: 'Sorcova s’intéresse-t-elle uniquement au stress ?', a: 'Non. Le stress est un point de départ important, pas toute l’histoire. Sorcova relie la résilience au stress, le bien-être mental et la santé physique dans une perspective de santé durable. Sommeil, mouvement, alimentation, récupération et liens y ont leur place. Les particuliers comme les organisations peuvent explorer un programme.' },
        { q: 'Que se passe-t-il au démarrage ?', a: 'Une introduction guidée permet à Sorcova de vous connaître. Une phase de fondation construit ensuite votre référence personnelle. Durant cette période, l’accent est mis sur l’engagement et la progression, avant l’accès aux lectures personnelles.' },
        { q: 'Que m’apporte le kit biologique du stress ?', a: 'Le kit salivaire fournit des informations biologiques qu’un médecin examine. Votre Stress Signature vous est communiquée dans un compte rendu signé par un médecin. Le kit seul ne fournit ni diagnostic ni niveau clinique dans l’application.' },
        { q: 'Ava remplace-t-elle un clinicien ?', a: 'Non. Ava est un guide conçu pour utiliser des formulations signées par des cliniciens. Elle n’est pas médecin et ne donne pas de conseil médical. Les décisions cliniques restent du ressort d’un médecin.' },
        { q: 'Mon employeur peut-il voir mes résultats ?', a: 'Non. Vos résultats de santé individuels ne sont pas partagés avec votre employeur. La vue employeur est conçue pour les tendances agrégées, séparément de vos informations personnelles et cliniques.' },
        { q: 'Comment démarrer pour notre organisation ?', a: 'Commençons par un échange sur vos équipes, vos priorités et le périmètre du programme. Ensemble, nous pouvons explorer une introduction à Sorcova adaptée à votre organisation.' },
      ],
    },
    closing: { label: 'Votre prochain chapitre', title: 'Votre santé.\nDans la durée.', text: 'Un début personnel. Une vision plus large. Pour vous et pour les personnes avec qui vous travaillez.', member: 'Parlons de vous', employer: 'Parlons de vos équipes' },
    footer: { tagline: 'Cultiver une longévité en bonne santé.', privacy: 'Notre approche de la confidentialité', faq: 'Questions fréquentes', top: 'Retour en haut', copyright: 'Sorcova Health', language: 'Choisir votre langue' },
    contact: {
      title: 'Trouvons votre point de départ.',
      memberTitle: 'Un échange autour de vous.', employerTitle: 'Un échange autour de vos équipes.',
      memberText: 'Dites-nous ce que vous souhaitez explorer. Merci de ne pas inclure d’informations médicales.',
      employerText: 'Présentez votre organisation et ce que vous souhaitez explorer. Merci de ne pas inclure d’informations de santé individuelles.',
      name: 'Votre nom', email: 'Votre adresse e-mail', organisation: 'Organisation', message: 'Que souhaitez-vous explorer ?', optional: 'Facultatif',
      submit: 'Préparer l’e-mail', save: 'Enregistrer le brouillon',
      draftNote: 'Le brouillon est enregistré sur votre appareil. Rien n’est envoyé à Sorcova.',
      emailNote: 'Ouvre votre messagerie avec un brouillon à relire et à envoyer.',
      saved: 'Votre brouillon a été téléchargé. Rien n’a été envoyé.',
      prepared: 'Relisez et envoyez le brouillon dans votre messagerie. Rien n’est envoyé automatiquement.',
      fallback: 'Si votre messagerie ne s’ouvre pas, vous pouvez enregistrer le brouillon.',
      subjectMember: 'Une demande à propos de Sorcova pour moi', subjectEmployer: 'Une demande à propos de Sorcova pour notre organisation',
    },
    notFound: { title: 'Un petit détour.', text: 'Cette page est introuvable. Retrouvons le chemin de Sorcova.', link: 'Retour à l’accueil' },
  },
};
